name: Test benchmark matrix

on:
  workflow_dispatch:
  schedule:
    # daily at 2:00 AM UTC
    - cron: "0 2 * * *"

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04", "macos-10.15", "windows-2019" ]
        java: [ 11,12,13,14,15 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run becnhamrk
        uses: eskatos/gradle-command-action@v1
        with:
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: -Pjava.version=${{ matrix.java }} -Pbenchmark.requests=60000
